apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cx1fh174n-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-7528f76e5a.70f7.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:4bd7ec82c3d9d1b95669727c06dcfa7d31f171b8@sha256:d1d8363dda1e18ec08a95337bd1524b575d89828c9841ee1efb1555d4419aa6e
          name: container-image
